name: Run Python App

on:
  push:

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt || echo "No requirements file"

      - run: python what.py
